spring:
  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=10.50.84.15)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=XEPDB1)))
    username: CLC
    password: CLC#2021
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
        show_sql: true
    database-platform: org.hibernate.dialect.OracleDialect
  data:
    redis:
      port: 6388
      password: Dstk@2024